item {
    id: 1
    name: 'ezel'
}
item {
    id: 2
    name: 'hond'
}
item {
    id: 3
    name: 'koe'
}
item {
    id: 4
    name: 'kuiken'
}
item {
    id: 5
    name: 'paard'
}
item {
    id: 6
    name: 'schaap'
}
item {
    id: 7
    name: 'varken'
}